#!/bin/bash

secs=5
num_teams=6

while ((1)); do
	num_nodes=`mysql -ucyberstorm -pcyberstorm cyberstorm -e "select count(id) from nodes where timestamp_down is null" | tail -n 1`
	num_attacks=0
	if ((num_nodes >= 2)); then
		num_attacks=$((RANDOM % num_nodes))
	fi

	echo "$num_nodes nodes up; generating $num_attacks attacks"
	for ((i=0; i<num_attacks; i++)); do
		src_id=$((RANDOM % num_teams + 1))
		dst_id=$src_id
		while ((dst_id == src_id)); do
			dst_id=$((RANDOM % num_teams + 1))
		done
		src=`mysql -ucyberstorm -pcyberstorm cyberstorm -e "select id from nodes where team_id=$src_id order by rand() limit 1" | tail -n 1`
		dst=`mysql -ucyberstorm -pcyberstorm cyberstorm -e "select id from nodes where team_id=$dst_id order by rand() limit 1" | tail -n 1`

		mysql -ucyberstorm -pcyberstorm cyberstorm -e "insert into attacks values(null,$src,$dst,null)"
	done

	echo "Sleeping..."
	sleep $secs
done
